# Generated by Django 5.1.1 on 2024-12-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=15, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('patient_phn', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('scan', models.ImageField(upload_to='scans/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
