# Generated by Django 5.1.1 on 2024-12-18 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identity', models.CharField(max_length=15, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('user_phn', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('had_implants_before', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status_of_prediction', models.CharField(default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan', models.ImageField(upload_to='scans/')),
                ('type_of_scan', models.IntegerField(choices=[(1, 'MLO'), (0, 'CC')], default=1)),
                ('view_of_scan', models.IntegerField(choices=[(1, 'Left'), (0, 'Right')], default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='diagnostics.diagnostic')),
            ],
        ),
    ]
