# Generated by Django 5.1.1 on 2024-12-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='patient_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='diagnostic',
            old_name='patient_name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='diagnostic',
            old_name='patient_phn',
            new_name='user_phn',
        ),
    ]
