# Generated by Django 5.1.1 on 2024-12-11 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_diagnostic_status_of_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic',
            name='scan',
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan', models.ImageField(upload_to='scans/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='diagnostics.diagnostic')),
            ],
        ),
    ]
