# Generated by Django 5.1.1 on 2024-12-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
