# Generated by Django 5.1.1 on 2024-12-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='had_implants_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='scan',
            name='type_of_scan',
            field=models.CharField(choices=[('MLO', 'MLO'), ('CC', 'CC')], default='MLO', max_length=3),
        ),
        migrations.AddField(
            model_name='scan',
            name='view_of_scan',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], default='Left', max_length=5),
        ),
    ]
