# Generated by Django 5.1.1 on 2024-12-18 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0007_diagnostic_had_implants_before_scan_type_of_scan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='user_id',
            new_name='user_phone',
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='had_implants_before',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='scan',
            name='type_of_scan',
            field=models.IntegerField(choices=[(1, 'MLO'), (0, 'CC')], default=1),
        ),
        migrations.AlterField(
            model_name='scan',
            name='view_of_scan',
            field=models.IntegerField(choices=[(1, 'Left'), (0, 'Right')], default=1),
        ),
    ]
