# Generated by Django 5.1.1 on 2024-12-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0008_rename_user_id_diagnostic_user_phone_diagnostic_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic',
            name='user_phn',
        ),
    ]
